const questions = [

/* ================= HTML ================= */
{
  category: "HTML",
  questions: [
    { question: "What does HTML stand for?", options: ["Hyper Text Pre Processor","Hyper Text Markup Language","Hyper Tool Multi Language","Hyper Text Multiple Language"], correctAnswer: 1 },
    { question: "Which tag is used for link?", options: ["<link>","<a>","<href>","<url>"], correctAnswer: 1 },
    { question: "Which tag inserts image?", options: ["<image>","<src>","<img>","<pic>"], correctAnswer: 2 },
    { question: "Heading tag range?", options: ["<head>","<h1>-<h6>","<title>","<p>"], correctAnswer: 1 },
    { question: "Semantic element?", options: ["<div>","<span>","<b>","<section>"], correctAnswer: 3 },
    { question: "Line break tag?", options: ["<break>","<br>","<lb>","<newline>"], correctAnswer: 1 },
    { question: "Paragraph tag?", options: ["<para>","<text>","<p>","<pg>"], correctAnswer: 2 },
    { question: "Bold text tag?", options: ["<bold>","<b>","<stronger>","<bt>"], correctAnswer: 1 },
    { question: "Italic tag?", options: ["<italic>","<it>","<i>","<emphasis>"], correctAnswer: 2 },
    { question: "Create list?", options: ["<list>","<li>","<ul>","<ol>"], correctAnswer: 2 },
    { question: "Table row?", options: ["<td>","<tr>","<th>","<row>"], correctAnswer: 1 },
    { question: "Table data?", options: ["<tr>","<th>","<td>","<cell>"], correctAnswer: 2 },
    { question: "Form tag?", options: ["<input>","<submit>","<form>","<button>"], correctAnswer: 2 },
    { question: "Input type text?", options: ["string","text","input","txt"], correctAnswer: 1 },
    { question: "Checkbox type?", options: ["check","box","checkbox","tick"], correctAnswer: 2 },
    { question: "Radio type?", options: ["select","radio","option","circle"], correctAnswer: 1 },
    { question: "Button tag?", options: ["<btn>","<click>","<button>","<submit>"], correctAnswer: 2 },
    { question: "Meta tag use?", options: ["Design","SEO","Script","Style"], correctAnswer: 1 },
    { question: "Head section?", options: ["<header>","<top>","<head>","<meta>"], correctAnswer: 2 },
    { question: "Body tag?", options: ["<main>","<body>","<section>","<page>"], correctAnswer: 1 },
    { question: "HTML version?", options: ["HTML4","HTML5","HTML3","HTML2"], correctAnswer: 1 },
    { question: "Doctype?", options: ["<doctype>","<!DOCTYPE html>","<html5>","<doc>"], correctAnswer: 1 },
    { question: "Anchor attribute?", options: ["src","href","link","url"], correctAnswer: 1 },
    { question: "Image attribute?", options: ["href","src","link","alt"], correctAnswer: 1 },
    { question: "Alt attribute?", options: ["Link","Alternative text","Style","Script"], correctAnswer: 1 },
    { question: "Iframe tag?", options: ["<frame>","<iframe>","<if>","<embed>"], correctAnswer: 1 },
    { question: "Audio tag?", options: ["<sound>","<audio>","<music>","<mp3>"], correctAnswer: 1 },
    { question: "Video tag?", options: ["<movie>","<media>","<video>","<clip>"], correctAnswer: 2 },
    { question: "Comment?", options: ["//","<!-- -->","/* */","#"], correctAnswer: 1 },
    { question: "HTML file ext?", options: [".ht",".html",".web",".doc"], correctAnswer: 1 }
  ]
},

/* ================= CSS ================= */
{
  category: "CSS",
  questions: [
    { question: "CSS stands for?", options: ["Creative Style","Cascading Style Sheets","Color Sheet","Computer Style"], correctAnswer: 1 },
    { question: "Text color?", options: ["font","text","color","bg"], correctAnswer: 2 },
    { question: "Background color?", options: ["bgcolor","background-color","color","background"], correctAnswer: 1 },
    { question: "Class selector?", options: ["#class",".class","*class","class"], correctAnswer: 1 },
    { question: "ID selector?", options: [".id","#id","*id","id"], correctAnswer: 1 },
    { question: "Margin?", options: ["Inner space","Outer space","Border","Padding"], correctAnswer: 1 },
    { question: "Padding?", options: ["Outer space","Inner space","Border","Gap"], correctAnswer: 1 },
    { question: "Display flex?", options: ["block","flex","inline","grid"], correctAnswer: 1 },
    { question: "Position absolute?", options: ["relative","absolute","fixed","sticky"], correctAnswer: 1 },
    { question: "Font size?", options: ["size","font-size","text-size","font"], correctAnswer: 1 },
    { question: "Border?", options: ["line","border","outline","edge"], correctAnswer: 1 },
    { question: "Overflow?", options: ["flow","overflow","scroll","hidden"], correctAnswer: 1 },
    { question: "Z-index?", options: ["index","z-index","layer","depth"], correctAnswer: 1 },
    { question: "Opacity?", options: ["transparent","opacity","alpha","visible"], correctAnswer: 1 },
    { question: "Flex direction?", options: ["column","row","both","none"], correctAnswer: 1 },
    { question: "Grid?", options: ["grid","display:grid","layout","table"], correctAnswer: 1 },
    { question: "Text align?", options: ["align","text-align","center","text"], correctAnswer: 1 },
    { question: "Font family?", options: ["font","font-family","family","text"], correctAnswer: 1 },
    { question: "Hover?", options: [":click",":hover",":active",":focus"], correctAnswer: 1 },
    { question: "Transition?", options: ["animation","transition","move","effect"], correctAnswer: 1 },
    { question: "Animation?", options: ["@animation","@keyframes","@move","@effect"], correctAnswer: 1 },
    { question: "Box model?", options: ["layout","margin,padding,border,content","design","grid"], correctAnswer: 1 },
    { question: "Width?", options: ["size","width","length","w"], correctAnswer: 1 },
    { question: "Height?", options: ["size","height","length","h"], correctAnswer: 1 },
    { question: "Cursor pointer?", options: ["hand","pointer","click","mouse"], correctAnswer: 1 },
    { question: "Float?", options: ["align","float","position","move"], correctAnswer: 1 },
    { question: "Clear?", options: ["remove","clear","reset","none"], correctAnswer: 1 },
    { question: "Shadow?", options: ["shadow","box-shadow","effect","blur"], correctAnswer: 1 },
    { question: "Text shadow?", options: ["shadow","text-shadow","effect","blur"], correctAnswer: 1 },
    { question: "Media query?", options: ["@screen","@media","@responsive","@mobile"], correctAnswer: 1 }
  ]
},

/* ================= JS ================= */
{
  category: "JS",
  questions: [
    { question: "Variable declare?", options: ["int","var","string","letx"], correctAnswer: 1 },
    { question: "Modern keyword?", options: ["var","let","int","char"], correctAnswer: 1 },
    { question: "Constant?", options: ["let","const","var","fixed"], correctAnswer: 1 },
    { question: "Function?", options: ["def","function","func","method"], correctAnswer: 1 },
    { question: "Console log?", options: ["print()","console.log()","echo","log()"], correctAnswer: 1 },
    { question: "Array?", options: ["{}","[]","()","<>"], correctAnswer: 1 },
    { question: "Object?", options: ["[]","{}","()","<>"], correctAnswer: 1 },
    { question: "Loop?", options: ["loop","for","repeat","cycle"], correctAnswer: 1 },
    { question: "While loop?", options: ["loop","while","repeat","cycle"], correctAnswer: 1 },
    { question: "Break?", options: ["stop","break","exit","end"], correctAnswer: 1 },
    { question: "Continue?", options: ["skip","continue","next","pass"], correctAnswer: 1 },
    { question: "Map?", options: ["loop()","map()","each()","iterate()"], correctAnswer: 1 },
    { question: "Filter?", options: ["remove()","filter()","clean()","select()"], correctAnswer: 1 },
    { question: "forEach?", options: ["each()","forEach()","loop()","run()"], correctAnswer: 1 },
    { question: "Typeof?", options: ["type","typeof","check","var"], correctAnswer: 1 },
    { question: "Strict equal?", options: ["==","===","=","!="], correctAnswer: 1 },
    { question: "Arrow function?", options: ["->","=>","=>=","=>>"], correctAnswer: 1 },
    { question: "DOM select?", options: ["get","querySelector","select","find"], correctAnswer: 1 },
    { question: "Event?", options: ["run","click","do","exec"], correctAnswer: 1 },
    { question: "JSON parse?", options: ["parseJSON","JSON.parse","readJSON","decode"], correctAnswer: 1 },
    { question: "JSON stringify?", options: ["stringJSON","JSON.stringify","encode","convert"], correctAnswer: 1 },
    { question: "LocalStorage?", options: ["storage","localStorage","save","cache"], correctAnswer: 1 },
    { question: "Set item?", options: ["addItem","setItem","store","push"], correctAnswer: 1 },
    { question: "Get item?", options: ["fetch","getItem","read","pull"], correctAnswer: 1 },
    { question: "Promise?", options: ["Async","Promise","Future","Wait"], correctAnswer: 1 },
    { question: "Async?", options: ["await","async","promise","then"], correctAnswer: 1 },
    { question: "Await?", options: ["wait","await","hold","pause"], correctAnswer: 1 },
    { question: "SetTimeout?", options: ["delay","setTimeout","timer","wait"], correctAnswer: 1 },
    { question: "SetInterval?", options: ["loop","setInterval","repeat","timer"], correctAnswer: 1 },
    { question: "NaN?", options: ["Null","Not a Number","Zero","Error"], correctAnswer: 1 }
  ]
},

/* ================= PHP ================= */
{
  category: "PHP",
  questions: [
    { question: "PHP stands for?", options: ["Personal Home Page","Hypertext Preprocessor","Private Home Page","Preprocessor Home Page"], correctAnswer: 1 },
    { question: "Variable symbol?", options: ["#","$","@","&"], correctAnswer: 1 },
    { question: "Echo?", options: ["print","echo","show","log"], correctAnswer: 1 },
    { question: "Print?", options: ["echo","print","write","display"], correctAnswer: 1 },
    { question: "Array?", options: ["[]","array()","{}","<>"], correctAnswer: 1 },
    { question: "Function?", options: ["def","function","func","method"], correctAnswer: 1 },
    { question: "If?", options: ["when","if","check","cond"], correctAnswer: 1 },
    { question: "Else?", options: ["otherwise","else","other","next"], correctAnswer: 1 },
    { question: "Loop?", options: ["loop","for","repeat","cycle"], correctAnswer: 1 },
    { question: "While?", options: ["loop","while","repeat","cycle"], correctAnswer: 1 },
    { question: "Foreach?", options: ["for","foreach","each","loop"], correctAnswer: 1 },
    { question: "Include?", options: ["import","include","require","add"], correctAnswer: 1 },
    { question: "Require?", options: ["include","require","import","add"], correctAnswer: 1 },
    { question: "GET?", options: ["$_POST","$_GET","$_REQ","$_DATA"], correctAnswer: 1 },
    { question: "POST?", options: ["$_GET","$_POST","$_DATA","$_REQ"], correctAnswer: 1 },
    { question: "Session?", options: ["$_COOKIE","$_SESSION","$_DATA","$_VAR"], correctAnswer: 1 },
    { question: "Cookie?", options: ["$_SESSION","$_COOKIE","$_DATA","$_VAR"], correctAnswer: 1 },
    { question: "String?", options: ["text","string","char","word"], correctAnswer: 1 },
    { question: "Integer?", options: ["number","int","digit","num"], correctAnswer: 1 },
    { question: "Boolean?", options: ["yes/no","true/false","1/0","all"], correctAnswer: 1 },
    { question: "Concat?", options: ["+",".","&","*"], correctAnswer: 1 },
    { question: "Comment?", options: ["//","#","/* */","All"], correctAnswer: 3 },
    { question: "File ext?", options: [".html",".php",".js",".css"], correctAnswer: 1 },
    { question: "Server side?", options: ["No","Yes","Both","None"], correctAnswer: 1 },
    { question: "Database?", options: ["MongoDB","MySQL","Oracle","All"], correctAnswer: 3 },
    { question: "Connect DB?", options: ["connect","mysqli","db","link"], correctAnswer: 1 },
    { question: "Close DB?", options: ["end()","close()","stop()","finish()"], correctAnswer: 1 },
    { question: "Header?", options: ["head()","header()","top()","meta()"], correctAnswer: 1 },
    { question: "Die?", options: ["exit()","die()","stop()","kill()"], correctAnswer: 1 },
    { question: "Exit?", options: ["die()","exit()","stop()","end()"], correctAnswer: 1 }
  ]
}

];